### ISSUE TITLE
async file write

### ISSUE THREAD

**Issue by Julien00859** [asvetlov/us-pycon-2019-tutorial#9]
Hello :)

Little question according to the following function:

https://github.com/asvetlov/us-pycon-2019-tutorial/blob/9c959d9814a149ae6b3ba577c87f5e313c36942b/code/02-intro-aiohttp/aiohttp_demo.py#L18-L23

If I'm not mistaken, write() is synchronous. Is there something magic done by python that will asynchronously write the file when it is in a coroutine or is the function a coroutine just for the demo ?

Regards,

**Comment by asvetlov** [comment]
Thanks for the interesting question.
Strictly speaking *blocking IO call* doesn't make sense (but is used for sake of simplicity very wide).
The real asyncio requirement is: any callback function (or code piece executed between two subsequent `await` calls) should be executed relatively quickly (100ms is a reasonable *red flag* barrier).

Short files on a local drive fit to this requirement pretty well. Very long files or remote disk storage like NFS or SMB violates the restriction very often.

Also please keep in mind: this is a tutorial, which means a compromise between code size and 100% correctness. 
Complicating a code (even by introducing a relatively simple library like `aiofiles`) is not the tutorial target. Especially taking into account that `aiofiles` is not 100% compatible drop-in replacement for standard python io system.

`write_to_file` *can* be converted into a regular function in this particular case, sure.
On the other hand, in my experience better to *reserve* `async def` for code which can be asynchronous potentially, it simplifies future refactoring.
Consider that you want to replace file system with blob storage like Amazon S3 eventually. The task is easy if your system is built from async blocks but converting a big amount of nested sync calls into asynchronous ones can make a challenge.

**Comment by Julien00859** [comment]
I thought any kind of IO *had* to be asynchronous in order to not block the event loop without considering the effective time spent on the IO. Thank you for the complete explanation, it really makes sense to ease a possible refactor. :+1:
